#!/bin/sh
echo "i am /etc/runit/2 file "

echo "i am registering trap "

sv_stop() {
      echo "I received SIGTERM"
}

#trap UserSig1 SIGUSR1
trap sv_stop SIGTERM

exec runsvdir -P /etc/service &
wait
echo date
echo "2:i amg oing to stop  "