#!/bin/sh

echo "STAGE 2: starting ..............."

echo "i am registering trap "

cont_sv() {
      echo "STAGE 2: I received SIGCONT"
}

term_sv() {
      echo "STAGE 2: I received SIGTERM"
}
kill_sv() {
      echo "STAGE 2: I received SIGUSR1"
}
#trap kill_sv SIGUSR1
#trap kill_sv SIGKILL
#trap term_sv SIGTERM
#trap cont_sv SIGCONT

exec runsvdir /etc/service
echo date
echo "STAGE 2: stopped.........."